### ISSUE TITLE
skills line 27 28

### ISSUE THREAD

**Issue by Shayds34** [Shayds34/Zombicide#2]
Ligne 27 28, il y a un skill Bloodlust et un Melee. 
Comme je vois autour qu'il y a souvent Bloodlust: Action dans le même skill, je me demandais si tu avais pas manqué un cran ?

**Comment by Sederikku** [comment]
Oui je m'en suis rendu compte quand il me manquait un autre skill : C'est corrigé.
J'ai aussi fait un beautify du texte y'avait quelques erreurs de saut de ligne.
